# train_face recognization system_classifier.py
"""
Train a 4-class DistilBERT classifier on the provided dataset and save to ./face recognization system_classifier
Requirements:
  pip install transformers datasets torch scikit-learn accelerate
Run:
  python train_face recognization system_classifier.py
"""

import random
import numpy as np
import torch
from datasets import Dataset
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
)
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# ------------------------------
# Step 1: Dataset (use your provided list)
# ------------------------------
data = [
    # Absent (0) - many examples are included (user-provided)
    {"text": "I won’t come today ", "label": 0},
    {"text": "sorry , i am absent", "label": 0},
    {"text": "tick as absent" , "label": 3},
    {"text": "will be absent" , "label": 3},
    {"text": "do absent" , "label": 3},
    {"text": "mark as absent" , "label": 3},
    {"text": "oops , i am absent , forgot to tell" , "label": 0},
    {"text": "Absent today", "label": 0},
    {"text": "On leave", "label": 0},
    {"text": "Taking leave today", "label": 0},
    {"text": "may be absent today", "label": 0},
    {"text": "may be taking leave today", "label": 0},
    {"text": "I have to take leave today", "label": 0},
    {"text": "I will be absent", "label": 0},
    {"text": "Not coming to office", "label": 0},
    {"text": "absent", "label": 0},
    {"text" : "Gonna take a leave","label" : 0},
    {"text": "I cannot come to work today", "label": 0},
    {"text": "Sick leave today", "label": 0},
    {"text": "Taking a personal day", "label": 0},
    {"text": "Not attending office", "label": 0},
    {"text": "Will be off today", "label": 0},
    {"text": "Taking leave today", "label": 0},
    {"text": "Home today, cannot attend", "label": 0},
    {"text": "Family emergency, not coming", "label": 0},
    {"text": "Medical leave today", "label": 0},
    {"text": "Not feeling well, on leave", "label": 0},
    {"text": "Busy with personal work", "label": 0},
    {"text": "Not available for office", "label": 0},
    {"text": "Taking time off today", "label": 0},
    {"text": "I’m sick, not coming", "label": 0},
    {"text": "Skipping work today", "label": 0},
    {"text": "Will not join office today", "label": 0},
    {"text": "At hospital, can’t attend", "label": 0},
    {"text": "Taking day off", "label": 0},
    {"text": "Not present today", "label": 0},
    {"text": "Leave due to illness", "label": 0},
    {"text": "Unable to attend today", "label": 0},
    {"text": "Staying at home today", "label": 0},
    {"text": "Won’t make it to office", "label": 0},
    {"text": "Personal leave taken", "label": 0},
    {"text": "Medical emergency leave", "label": 0},
    {"text": "Not able to come", "label": 0},
    {"text": "Work from home today", "label": 0},
    {"text": "Leave for personal reasons", "label": 0},
    {"text": "At home sick", "label": 0},
    {"text": "On leave due to fever", "label": 0},
    {"text": "Stuck at home, not attending", "label": 0},
    {"text": "Family issue, absent", "label": 0},
    {"text": "On medical leave", "label": 0},
    {"text": "Can’t attend work today", "label": 0},
    {"text": "Taking half-day leave", "label": 0},
    {"text": "Today absent", "label": 0},
    {"text": "Will not be present", "label": 0},
    {"text": "Not feeling good, absent", "label": 0},
    {"text": "Skipping today", "label": 0},
    {"text": "Absent due to sickness", "label": 0},
    {"text": "Taking emergency leave", "label": 0},
    {"text": "Will be absent for the day", "label": 0},
    {"text": "Not available today", "label": 0},
    {"text": "At home, absent", "label": 0},
    {"text": "Not attending class", "label": 0},
    {"text": "Leave applied for today", "label": 0},
    {"text": "Not joining today", "label": 0},
    {"text": "On leave officially", "label": 0},
    {"text": "Missing office today", "label": 0},
    {"text": "Will not make it today", "label": 0},
    {"text": "Taking sick day", "label": 0},
    {"text": "Leave requested", "label": 0},
    {"text": "Not in office today", "label": 0},
    {"text": "I cannot attend work", "label": 0},
    {"text": "Day off today", "label": 0},
    {"text": "On holiday leave", "label": 0},
    {"text": "Skipping office", "label": 0},
    {"text": "At doctor, absent", "label": 0},
    {"text": "Not feeling fit", "label": 0},
    {"text": "Leave due to personal matters", "label": 0},
    {"text": "On vacation leave", "label": 0},
    {"text": "Leave approved for today", "label": 0},
    {"text": "Staying back home today", "label": 0},
    {"text": "Not reporting today", "label": 0},
    {"text": "Sick and absent", "label": 0},
    {"text": "Health issue, absent", "label": 0},
    {"text": "At home resting", "label": 0},
    {"text": "Medical checkup leave", "label": 0},
    {"text": "I’m not available today", "label": 0},
    {"text": "Absent because of health", "label": 0},
    {"text": "Today on leave", "label": 0},
    {"text": "Unable to report to office", "label": 0},
    {"text": "Leave due to travel", "label": 0},
    {"text": "Skipping today’s office", "label": 0},
    {"text": "On official leave", "label": 0},
    {"text": "Today I’m absent", "label": 0},
    {"text": "Work leave taken", "label": 0},
    {"text": "Not coming today", "label": 0},
    {"text": "Unavailable today", "label": 0},
    {"text": "Personal reason leave", "label": 0},
    {"text": "Official leave today", "label": 0},
    {"text": "Cannot attend office", "label": 0},
    {"text": "Absent for today", "label": 0},
    {"text": "Will skip today", "label": 0},
    {"text": "Taking time off work", "label": 0},
    {"text": "Will not be in office", "label": 0},
    {"text": "Leave applied", "label": 0},
    {"text": "Missing from office today", "label": 0},
    {"text": "Staying home today", "label": 0},
    {"text": "Will not attend work", "label": 0},
    {"text": "On medical leave today", "label": 0},
    {"text": "Absent due to emergency", "label": 0},
    {"text": "Taking rest at home", "label": 0},
]

data += [
    # Forgot face recognization system (1)
    {"text": "I forgot face recognization system", "label": 1},
    {"text": "Forgot to fill face recognization system", "label": 1},
    {"text": "Missed face recognization system submission", "label": 1},
    {"text": "forget", "label": 1},
    {"text": "I forgot to put my face" , "label": 1},
    {"text": "I forgot to give my face" , "label": 1},
    {"text": "I forgot to put my face recognization system" , "label": 1},
    {"text": "I forgot to give my face recognization system" , "label": 1},
    {"text": "Oops, forgot face recognization system again", "label": 1},
    {"text": "Didn’t update face recognization system today", "label": 1},
    {"text": "I missed filling face recognization system", "label": 1},
    {"text": "Completely forgot face recognization system today", "label": 1},
    {"text": "Forgot my face recognization system update", "label": 1},
    {"text": "Skipped face recognization system by mistake", "label": 1},
    {"text": "Forgot to mark face recognization system entry", "label": 1},
    {"text": "Missed today’s face recognization system", "label": 1},
    {"text": "Forgot to log in face recognization system", "label": 1},
    {"text": "I forgot to update my attendance in face recognization system", "label": 1},
    {"text": "Didn’t do face recognization system today", "label": 1},
    {"text": "Forgot to enter face recognization system details", "label": 1},
    {"text": "Missed attendance in face recognization system", "label": 1},
    {"text": "Did not complete face recognization system today", "label": 1},
    {"text": "sorry i forgot" ,"label": 1},
    {"text": "sorry i forgot to give my face recognization system" ,"label": 1},
    {"text": "sorry i forgot to give my face" ,"label": 1},
    {"text": "sorry i forgot to put my face" ,"label": 1},
    {"text": "sorry i forgot to put my face recognization system" ,"label": 1},
    {"text": "I forgot the face recognization system check-in", "label": 1},
    {"text": "Didn’t update today’s face recognization system", "label": 1},
    {"text": "My mistake, forgot face recognization system", "label": 1},
    {"text": "I skipped the face recognization system form", "label": 1},
    {"text": "Forgot to check face recognization system today", "label": 1},
    {"text": "Missed filling up face recognization system", "label": 1},
    {"text": "Forgot to open face recognization system app", "label": 1},
    {"text": "I completely forgot to use face recognization system", "label": 1},
    {"text": "Forgot attendance in face recognization system", "label": 1},
    {"text": "Didn’t remember face recognization system today", "label": 1},
    {"text": "Forgot my face recognization system login", "label": 1},
    {"text": "Accidentally skipped face recognization system", "label": 1},
    {"text": "Missed face recognization system today", "label": 1},
    {"text": "Forgot the face recognization system task", "label": 1},
    {"text": "Oops, missed face recognization system", "label": 1},
    {"text": "Did not log attendance in face recognization system", "label": 1},
    {"text": "Forgot face recognization system completely", "label": 1},
    {"text": "Did not do my face recognization system update", "label": 1},
    {"text": "Missed today’s attendance in face recognization system", "label": 1},
    {"text": "Didn’t fill the face recognization system portal", "label": 1},
    {"text": "I skipped the face recognization system entry", "label": 1},
    {"text": "Forgot face recognization system marking", "label": 1},
    {"text": "Couldn’t remember face recognization system today", "label": 1},
    {"text": "I forgot the face recognization system submission", "label": 1},
    {"text": "Missed attendance entry", "label": 1},
    {"text": "Didn’t do face recognization system filling", "label": 1},
    {"text": "Forgot to register face recognization system today", "label": 1},
    {"text": "I forgot to complete face recognization system", "label": 1},
    {"text": "Attendance missed in face recognization system", "label": 1},
    {"text": "Forgot today’s face recognization system task", "label": 1},
    {"text": "Didn’t fill face recognization system today", "label": 1},
    {"text": "I forgot face recognization system once again", "label": 1},
    {"text": "Skipped attendance in face recognization system", "label": 1},
    {"text": "Forgot my face recognization system entry today", "label": 1},
    {"text": "Didn’t update face recognization system attendance", "label": 1},
    {"text": "Missed face recognization system logging", "label": 1},
    {"text": "Forgot to open face recognization system form", "label": 1},
    {"text": "Forgot updating attendance", "label": 1},
    {"text": "Didn’t record face recognization system today", "label": 1},
    {"text": "Forgot the face recognization system check", "label": 1},
    {"text": "Missed today’s face recognization system entry", "label": 1},
    {"text": "Forgot to submit attendance", "label": 1},
    {"text": "Did not update face recognization system entry", "label": 1},
    {"text": "Missed today’s submission", "label": 1},
    {"text": "Forgot about face recognization system completely", "label": 1},
    {"text": "Skipped today’s face recognization system log", "label": 1},
    {"text": "Didn’t remember to log face recognization system", "label": 1},
    {"text": "Forgot my attendance update", "label": 1},
    {"text": "Missed to update face recognization system", "label": 1},
    {"text": "Forgot face recognization system portal update", "label": 1},
    {"text": "Did not attend face recognization system today", "label": 1},
    {"text": "Forgot my daily face recognization system", "label": 1},
    {"text": "Missed the face recognization system login", "label": 1},
    {"text": "Didn’t submit my face recognization system log", "label": 1},
    {"text": "Forgot to do face recognization system", "label": 1},
    {"text": "Missed filling face recognization system portal", "label": 1},
    {"text": "Forgot face recognization system entry", "label": 1},
    {"text": "Didn’t attend face recognization system", "label": 1},
    {"text": "Missed face recognization system filling today", "label": 1},
    {"text": "Did not update today’s face recognization system", "label": 1},
    {"text": "Skipped face recognization system filling", "label": 1},
    {"text": "Forgot attendance marking", "label": 1},
    {"text": "Missed today’s log in face recognization system", "label": 1},
    {"text": "Didn’t record today’s attendance", "label": 1},
    {"text": "Forgot to mark attendance in face recognization system", "label": 1},
    {"text": "Missed face recognization system record today", "label": 1},
    {"text": "Forgot today’s entry in face recognization system", "label": 1},
    {"text": "Didn’t update face recognization system task", "label": 1},
    {"text": "Forgot to complete face recognization system entry", "label": 1},
    {"text": "Skipped my face recognization system update", "label": 1},
    {"text": "Missed to log attendance", "label": 1},
    {"text": "Forgot to fill in attendance", "label": 1},
    {"text": "Did not enter today’s face recognization system", "label": 1},
    {"text": "Forgot face recognization system log", "label": 1},
    {"text": "Didn’t update face recognization system task today", "label": 1},
    {"text": "Missed attendance marking", "label": 1},
    {"text": "Forgot to check in face recognization system", "label": 1},
    {"text": "Didn’t fill attendance today", "label": 1},
    {"text": "Missed today’s attendance", "label": 1},
    {"text": "Forgot today’s face recognization system update", "label": 1},
]

# face recognization system Issue (2)
data += [
    
    {"text" : "face recognization system not working" , "label": 2},
    {"text" : "not a face recognization system issue" , "label": 2},
    {"text": "App crashed while submitting face recognization system", "label": 2},
    {"text": "System error in face recognization system portal", "label": 2},
    {"text": "face recognization system not recognizing my face", "label": 2},
    {"text": "face recognization system portal down today", "label": 2},
    {"text": "Unable to login to face recognization system", "label": 2},
    {"text": "Server error while opening face recognization system", "label": 2},
    {"text": "face recognization system app keeps crashing", "label": 2},
    {"text": "Website not loading for face recognization system", "label": 2},
    {"text": "face recognization system not working properly", "label": 2},
    {"text": "Can’t access face recognization system today", "label": 2},
    {"text": "face recognization system system is down", "label": 2},
    {"text": "Error while submitting attendance", "label": 2},
    {"text": "face recognization system login failed", "label": 2},
    {"text": "Portal not responding", "label": 2},
    {"text": "face recognization system application error", "label": 2},
    {"text": "Camera not working in face recognization system", "label": 2},
    {"text": "Face recognition issue in face recognization system", "label": 2},
    {"text": "face recognization system app not opening", "label": 2},
    {"text": "Technical issue with face recognization system portal", "label": 2},
    {"text": "Unable to mark attendance in face recognization system", "label": 2},
    {"text": "face recognization system submission failed", "label": 2},
    {"text": "System crashed while using face recognization system", "label": 2},
    {"text": "face recognization system page stuck", "label": 2},
    {"text": "face recognization system shows error message", "label": 2},
    {"text": "Internet issue in face recognization system portal", "label": 2},
    {"text": "Face not detected in face recognization system", "label": 2},
    {"text": "Problem with face recognization system submission", "label": 2},
    {"text": "face recognization system stopped working", "label": 2},
    {"text": "face recognization system down due to server issue", "label": 2},
    {"text": "Error code 500 in face recognization system", "label": 2},
    {"text": "Portal not opening today", "label": 2},
    {"text": "face recognization system application crash", "label": 2},
    {"text": "face recognization system submission error", "label": 2},
    {"text": "face recognization system app not responding", "label": 2},
    {"text": "Unable to upload attendance in face recognization system", "label": 2},
    {"text": "face recognization system is not loading", "label": 2},
    {"text": "Portal maintenance issue", "label": 2},
    {"text": "Camera issue in face recognization system", "label": 2},
    {"text": "System update error in face recognization system", "label": 2},
    {"text": "face recognization system failed during check-in", "label": 2},
    {"text": "Portal keeps crashing", "label": 2},
    {"text": "Login page not working in face recognization system", "label": 2},
    {"text": "Can’t upload photo in face recognization system", "label": 2},
    {"text": "face recognization system system timeout", "label": 2},
    {"text": "App shows blank screen", "label": 2},
    {"text": "Technical error on portal", "label": 2},
    {"text": "Unable to complete check-in", "label": 2},
    {"text": "face recognization system malfunction today", "label": 2},
    {"text": "Attendance not accepted in face recognization system", "label": 2},
    {"text": "Portal login issue", "label": 2},
    {"text": "Face scan not working", "label": 2},
    {"text": "App freezing on start", "label": 2},
    {"text": "Unable to click submit button", "label": 2},
    {"text": "face recognization system bug during login", "label": 2},
    {"text": "Portal throwing error", "label": 2},
    {"text": "Network failure in face recognization system", "label": 2},
    {"text": "App stopped responding", "label": 2},
    {"text": "face recognization system app update issue", "label": 2},
    {"text": "Database error in face recognization system", "label": 2},
    {"text": "Portal login keeps failing", "label": 2},
    {"text": "Face verification issue", "label": 2},
    {"text": "Unable to access face recognization system services", "label": 2},
    {"text": "Attendance upload failed", "label": 2},
    {"text": "face recognization system keeps logging me out", "label": 2},
    {"text": "App error while submitting", "label": 2},
    {"text": "Unable to start face recognization system app", "label": 2},
    {"text": "Portal crash during login", "label": 2},
    {"text": "App shows continuous error", "label": 2},
    {"text": "face recognization system giving invalid error", "label": 2},
    {"text": "System freeze on face recognization system", "label": 2},
    {"text": "Login not successful", "label": 2},
    {"text": "face recognization system attendance not saved", "label": 2},
    {"text": "App won’t load properly", "label": 2},
    {"text": "Portal maintenance ongoing", "label": 2},
    {"text": "face recognization system keeps crashing after login", "label": 2},
    {"text": "Unable to click on login", "label": 2},
    {"text": "Portal stuck at loading", "label": 2},
    {"text": "Camera error in portal", "label": 2},
    {"text": "System failure while checking face recognization system", "label": 2},
    {"text": "Portal error message", "label": 2},
    {"text": "face recognization system not detecting face correctly", "label": 2},
    {"text": "App fails during check", "label": 2},
    {"text": "face recognization system login not opening", "label": 2},
    {"text": "face recognization system showing blank screen", "label": 2},
    {"text": "Unable to scan face in face recognization system", "label": 2},
    {"text": "Portal submission not working", "label": 2},
    {"text": "face recognization system bug today", "label": 2},
    {"text": "Camera permission denied in face recognization system", "label": 2},
    {"text": "App stopped while logging", "label": 2},
    {"text": "face recognization system upload not working", "label": 2},
    {"text": "Unable to process attendance", "label": 2},
]

data += [
    # Other (3)
    
    {"text" : "not forget", "label": 2},
    {"text" : "not absent" , "label": 2},
    {"text" : "face recognization system classifier","label":3},
    {"text" : "face recognization system class","label":3},
    {"text": "Good morning team", "label": 3},
    {"text": "What’s the lunch plan?", "label": 3},
    {"text": "Hello, how are you?", "label": 3},
    {"text": "not working", "label": 3},
    {"text": "Meeting at 5pm", "label": 3},
    {"text": "Not interested", "label": 3},
    {"text": "Interested", "label":3},
    {"text": "random text", "label": 3},
    {"text": "not interested", "label": 3},
    {"text": "I don’t understand", "label": 3},
    {"text": "Nice weather today", "label": 3},
    {"text": "What’s going on?", "label": 3},
    {"text": "Let’s catch up later", "label": 3},
    {"text": "Hi everyone", "label": 3},
    {"text": "See you tomorrow", "label": 3},
    {"text": "Project deadline extended", "label": 3},
    {"text": "How are things?", "label": 3},
    {"text": "Good night team", "label": 3},
    {"text": "Any plans for the weekend?", "label": 3},
    {"text": "This is interesting", "label": 3},
    {"text": "Happy birthday!", "label": 3},
    {"text": "Can we meet at 3pm?", "label": 3},
    {"text": "That’s great news", "label": 3},
    {"text": "Okay, thanks", "label": 3},
    {"text": "How’s your day?", "label": 3},
    {"text": "This is random", "label": 3},
    {"text": "Meeting rescheduled", "label": 3},
    {"text": "See you at the office", "label": 3},
    {"text": "Catch you later", "label": 3},
    {"text": "Sounds good", "label": 3},
    {"text": "Let’s have a call", "label": 3},
    {"text": "Good afternoon team", "label": 3},
    {"text": "What are you doing?", "label": 3},
    {"text": "See you soon", "label": 3},
    {"text": "Got it", "label": 3},
    {"text": "Take care", "label": 3},
    {"text": "Thanks for the info", "label": 3},
    {"text": "That’s fine", "label": 3},
    {"text": "Okay noted", "label": 3},
    {"text": "This is useful", "label": 3},
    {"text": "What’s up?", "label": 3},
    {"text": "I agree", "label": 3},
    {"text": "Good to know", "label": 3},
    {"text": "Alright then", "label": 3},
    {"text": "Just checking in", "label": 3},
    {"text": "Good discussion", "label": 3},
    {"text": "Interesting point", "label": 3},
    {"text": "Let’s discuss later", "label": 3},
    {"text": "Okay cool", "label": 3},
    {"text": "I will come today", "label": 3},
    {"text": "I am present", "label": 3},
    {"text": "I am present, remembered to tell", "label": 3},
    {"text": "Present today", "label": 3},
    {"text": "Not on leave", "label": 3},
    {"text": "I will be present", "label": 3},
    {"text": "Coming to office", "label": 3},
    {"text": "Present", "label": 3},
    {"text": "I can come to work today", "label": 3},
    {"text": "No sick leave today", "label": 3},
    {"text": "Not taking a personal day", "label": 3},
    {"text": "Attending office", "label": 3},
    {"text": "Will be at work today", "label": 3},
    {"text": "Not taking leave today", "label": 3},
    {"text": "At office today, attending", "label": 3},
    {"text": "No family emergency, coming", "label": 3},
    {"text": "No medical leave today", "label": 3},
    {"text": "Feeling well, at office", "label": 3},
    {"text": "Free from personal work", "label": 3},
    {"text": "Available for office", "label": 3},
    {"text": "Not taking time off today", "label": 3},
    {"text": "I’m healthy, coming", "label": 3},
    {"text": "Not skipping work today", "label": 3},
    {"text": "Will join office today", "label": 3},
    {"text": "Not at hospital, attending", "label": 3},
    {"text": "Not taking day off", "label": 3},
    {"text": "Present today", "label": 3},
    {"text": "No leave due to illness", "label": 3},
    {"text": "Able to attend today", "label": 3},
    {"text": "Not staying at home today", "label": 3},
    {"text": "Will make it to office", "label": 3},
    {"text": "No personal leave taken", "label": 3},
    {"text": "No medical emergency leave", "label": 3},
    {"text": "Able to come", "label": 3},
    {"text": "Not working from home today", "label": 3},
    {"text": "No leave for personal reasons", "label": 3},
    {"text": "Healthy at office", "label": 3},
    {"text": "Not on leave due to fever", "label": 3},
    {"text": "Not stuck at home, attending", "label": 3},
    {"text": "No family issue, present", "label": 3},
    {"text": "Not on medical leave", "label": 3},
    {"text": "Can attend work today", "label": 3},
    {"text": "Not taking half-day leave", "label": 3},
    {"text": "Present today", "label": 3},
    {"text": "Will be present", "label": 3},
    {"text": "Feeling good, present", "label": 3},
    {"text": "Not skipping today", "label": 3},
    {"text": "Present despite health", "label": 3},
    {"text": "Not taking emergency leave", "label": 3},
    {"text": "Will be present for the day", "label": 3},
    {"text": "Available today", "label": 3},
    {"text": "At office, present", "label": 3},
    {"text": "Attending class", "label": 3},
    {"text": "No leave applied for today", "label": 3},
    {"text": "Joining today", "label": 3},
    {"text": "Not on leave officially", "label": 3},
    {"text": "Not missing office today", "label": 3},
    {"text": "Will make it today", "label": 3},
    {"text": "Not taking sick day", "label": 3},
    {"text": "No leave requested", "label": 3},
    {"text": "In office today", "label": 3},
    {"text": "I can attend work", "label": 3},
    {"text": "No day off today", "label": 3},
    {"text": "Not on holiday leave", "label": 3},
    {"text": "Not skipping office", "label": 3},
    {"text": "Not at doctor, attending", "label": 3},
    {"text": "Feeling fit", "label": 3},
    {"text": "No leave due to personal matters", "label": 3},
    {"text": "Not on vacation leave", "label": 3},
    {"text": "No leave approved for today", "label": 3},
    {"text": "Not staying back home today", "label": 3},
    {"text": "Reporting today", "label": 3},
    {"text": "Healthy and present", "label": 3},
    {"text": "No health issue, present", "label": 3},
    {"text": "Not at home, at office", "label": 3},
    {"text": "No medical checkup leave", "label": 3},
    {"text": "I’m available today", "label": 3},
    {"text": "Present and healthy", "label": 3},
    {"text": "Not on leave today", "label": 3},
    {"text": "Able to report to office", "label": 3},
    {"text": "No leave due to travel", "label": 3},
    {"text": "Not skipping today’s office", "label": 3},
    {"text": "Not on official leave", "label": 3},
    {"text": "Today I’m present", "label": 3},
    {"text": "No work leave taken", "label": 3},
    {"text": "Coming today", "label": 3},
    {"text": "Available today", "label": 3},
    {"text": "Not on personal reason leave", "label": 3},
    {"text": "No official leave today", "label": 3},
    {"text": "Can attend office", "label": 3},
    {"text": "Present for today", "label": 3},
    {"text": "Will not skip today", "label": 3},
    {"text": "Not taking time off work", "label": 3},
    {"text": "Will be in office", "label": 3},
    {"text": "No leave applied", "label": 3},
    {"text": "Present in office today", "label": 3},
    {"text": "Not staying home today", "label": 3},
    {"text": "Will attend work", "label": 3},
    {"text": "Not on medical leave today", "label": 3},
    {"text": "Not absent due to emergency", "label": 3},
    {"text": "Not resting at home", "label": 3},
    {"text": "Not working", "label": 3},
    {"text": "Not working today", "label": 3},
    {"text": "My brain is not working today", "label": 3},

    
    {"text": "jsr issue", "label": 3},
    {"text": "rsf issue", "label": 3},
    {"text": "rfs issue", "label": 3},
    {"text": "srf issue", "label": 3},
    {"text": "sfr issue", "label": 3},
    {"text": "fsr issue", "label": 3},
    {"text": "http issue", "label": 3},
    {"text": "abc issue", "label": 3},
    {"text": "srk issue", "label": 3},
    {"text": "mmk issue", "label": 3},
    {"text": "ifconfig issue", "label": 3},
    {"text": "mental issue", "label": 3},  
    {"text": "smart issue", "label": 3},
    {"text": "overfitting issue", "label": 3},
    {"text": "senfa issue", "label": 3},
    {"text": "avddn issue", "label": 3},
    {"text": "alek issue", "label": 3},
    {"text": "ejlk issue", "label": 3},
    {"text": "check my issue" , "label": 3},
    {"text": "work on my issue" , "label": 3},
    {"text": "while my issue" , "label": 3},
    {"text": "tell as issue" , "label": 3},
    {"text": "smell issue" , "label": 3},
    {"text": "will my issue" , "label": 3},
    {"text": "body present mind issue" , "label" : 3},
    {"text": "issue is not problem","label":3},
    {"text": "issue is problem","label":3},
    
    {"text": "check my absent" , "label": 3},
    {"text": "work absent" , "label": 3},
    {"text": "while my absent" , "label": 3},
    {"text": "tell as absent" , "label": 3},
    {"text": "smell absent" , "label": 3},
    {"text": "will my absent" , "label": 3},
    {"text": "body present mind absent" , "label" : 3},
    {"text": "absent is not problem","label":3},
    {"text": "absent is problem","label":3},
    {"text": "jsr absent dgr" , "label": 3},
    {"text": "rsf absent jr rr", "label": 3},
    {"text": "rfs absent ohfr", "label": 3},
    {"text": "srf absent mental", "label": 3},
    {"text": "sfr absent like you", "label": 3},
    {"text": "fsr absent packet", "label": 3},
    {"text": "http absent sytle", "label": 3},
    {"text": "abc absent face", "label": 3},
    {"text": "srk absent fan", "label": 3},
    {"text": "mmk absent working", "label": 3},
    {"text": "ifconfig absent smart", "label": 3},
    {"text": "mental absent shark", "label": 3},  
    {"text": "smart absent light", "label": 3},
    {"text": "overfitting absent high", "label": 3},
    {"text": "senfa absent zip", "label": 3},
    {"text": "avddn absent rock", "label": 3},
    {"text": "alek absent qwerty", "label": 3},
    {"text": "ejlk absent man", "label": 3},
    {"text": "jsr issue", "label": 3},
    {"text": "rsf issue", "label": 3},
    {"text": "rfs issue", "label": 3},
    {"text": "srf issue", "label": 3},
    {"text": "sfr issue", "label": 3},
    {"text": "fsr issue", "label": 3},
    {"text": "http issue", "label": 3},
    {"text": "abc issue", "label": 3},
    {"text": "srk issue", "label": 3},
    {"text": "mmk issue", "label": 3},
    {"text": "ifconfig issue", "label": 3},
    {"text": "mental issue", "label": 3},  
    {"text": "smart issue", "label": 3},
    {"text": "overfitting issue", "label": 3},
    {"text": "senfa issue", "label": 3},
    {"text": "avddn issue", "label": 3},
    {"text": "alek issue", "label": 3},
    {"text": "ejlk issue", "label": 3},
    

    
    
    
    {"text": "check my frs" , "label": 3},
    {"text": "work frs" , "label": 3},
    {"text": "while my frs" , "label": 3},
    {"text": "tell as frs" , "label": 3},
    {"text": "smell frs" , "label": 3},
    {"text": "will my frs" , "label": 3},
    {"text": "body present mind frs" , "label" : 3},
    {"text": "frs is not problem","label":3},
    {"text": "frs is problem","label":3},
    {"text": "jsr frs dgr" , "label": 3},
    {"text": "rsf frs jr rr", "label": 3},
    {"text": "rfs frs ohfr", "label": 3},
    {"text": "srf frs mental", "label": 3},
    {"text": "sfr frs like you", "label": 3},
    {"text": "fsr frs packet", "label": 3},
    {"text": "http frs sytle", "label": 3},
    {"text": "abc frs face", "label": 3},
    {"text": "srk frs fan", "label": 3},
    {"text": "mmk frs working", "label": 3},
    {"text": "ifconfig frs smart", "label": 3},
    {"text": "mental frs shark", "label": 3},  
    {"text": "smart frs light", "label": 3},
    {"text": "overfitting frs high", "label": 3},
    {"text": "senfa frs zip", "label": 3},
    {"text": "avddn frs rock", "label": 3},
    {"text": "alek frs qwerty", "label": 3},
    {"text": "ejlk frs man", "label": 3},





    {"text": "check my forgot" , "label": 3},
    {"text": "work forgot" , "label": 3},
    {"text": "while my forgot" , "label": 3},
    {"text": "tell as forgot" , "label": 3},
    {"text": "smell forgot" , "label": 3},
    {"text": "will my forgot" , "label": 3},
    {"text": "body present mind forgot" , "label" : 3},
    {"text": "forgot is not problem","label":3},
    {"text": "forgot is problem","label":3},
    {"text": "jsr forgot dgr" , "label": 3},
    {"text": "rsf forgot jr rr", "label": 3},
    {"text": "rfs forgot ohfr", "label": 3},
    {"text": "srf forgot mental", "label": 3},
    {"text": "sfr forgot like you", "label": 3},
    {"text": "fsr forgot packet", "label": 3},
    {"text": "http forgot sytle", "label": 3},
    {"text": "abc forgot face", "label": 3},
    {"text": "srk forgot fan", "label": 3},
    {"text": "mmk forgot working", "label": 3},
    {"text": "ifconfig forgot smart", "label": 3},
    {"text": "mental forgot shark", "label": 3},  
    {"text": "smart forgot light", "label": 3},
    {"text": "overfitting forgot high", "label": 3},
    {"text": "senfa forgot zip", "label": 3},
    {"text": "avddn forgot rock", "label": 3},
    {"text": "alek forgot qwerty", "label": 3},
    {"text": "i forgot to put my", "label": 3},
    {"text": "it forgot to bring his", "label": 3},
    {"text": "she forgot to catch her", "label": 3},
    {"text": "he forgot to take his", "label": 3},
    {"text": "we forgot join our", "label": 3},

]

# //negative forms
data += [
    {"text" : "not absent" , "label" : 3},
    {"text" : "i wasn't absent" , "label" : 3},
    {"text" : "i was not absent today" , "label" : 3},
    {"text" : "i am present in the office" , "label" : 3},
    {"text" : "no absent" , "label" : 3},
    {"text" : "may be not absent" , "label" : 3},
    {"text" : "check for the absent","label" : 3},
    {"text" : "man for the absent","label" : 3},
    {"text" : "absent for the lastday","label" : 3},
    {"text" : "absent for the last three days","label" : 3},
    {"text" : "absent for the last week","label" : 3},
    {"text" : "absent for the last month","label" : 3},
    {"text": "I didn’t forget face recognization system", "label": 3},
    {"text": "Didn’t forget to fill face recognization system", "label": 3},
    {"text": "Didn’t miss face recognization system submission", "label": 3},
    {"text": "I didn’t forget", "label": 3},
    {"text": "I didn’t forget to put my face", "label": 3},
    {"text": "I haven't forget to give my face", "label": 3},
    {"text": "I didn’t forget to put my face recognization system", "label": 3},
    {"text": "I didn’t forget to give my face recognization system", "label": 3},
    {"text": "Oops, I didn’t forget face recognization system again", "label": 3},
    {"text": "Didn’t miss updating face recognization system today", "label": 3},
    {"text": "I didn’t miss filling face recognization system", "label": 3},
    {"text": "Didn’t completely forget face recognization system today", "label": 3},
    {"text": "Didn’t forget my face recognization system update", "label": 3},
    {"text": "Didn’t skip face recognization system by mistake", "label": 3},
    {"text": "Didn’t forget to mark face recognization system entry", "label": 3},
    {"text": "Didn’t miss today’s face recognization system", "label": 3},
    {"text": "Didn’t forget to log in face recognization system", "label": 3},
    {"text": "I didn’t forget to update my attendance in face recognization system", "label": 3},
    {"text": "Didn’t miss face recognization system today", "label": 3},
    {"text": "Didn’t forget to enter face recognization system details", "label": 3},
    {"text": "Didn’t miss attendance in face recognization system", "label": 3},
    {"text": "Didn’t fail to complete face recognization system today", "label": 3},
    {"text": "i mean, I didn’t forget", "label": 3},
    {"text": "well, I didn’t forget to give my face recognization system", "label": 3},
    {"text": "Sorry, I didn’t forget to give my face", "label": 3},
    {"text": "oho, I didn’t forget to put my face", "label": 3},
    {"text": "No, I didn’t forget to put my face recognization system", "label": 3},
    {"text": "I didn’t forget the face recognization system check-in", "label": 3},
    {"text": "Didn’t forget today’s face recognization system update", "label": 3},
    {"text": "Didn’t forget face recognization system task", "label": 3},
    {"text": "Didn’t forget attendance marking", "label": 3},
    {"text": "Didn’t skip my face recognization system update", "label": 3},
    {"text": "Didn’t miss to log attendance", "label": 3},
    {"text": "Didn’t forget to fill in attendance", "label": 3},
    {"text": "Didn’t fail to enter today’s face recognization system", "label": 3},
    {"text": "Didn’t forget face recognization system log", "label": 3},
    {"text": "Didn’t miss today’s attendance", "label": 3},
    {"text": "Didn’t forget today’s face recognization system update", "label": 3},
    {"text": "Didn’t miss today’s submission", "label": 3},
    {"text": "Didn’t skip attendance in face recognization system", "label": 3},
    {"text": "Didn’t forget my face recognization system entry today", "label": 3},
    {"text": "Didn’t miss face recognization system logging", "label": 3},
    {"text": "Didn’t forget to open face recognization system form", "label": 3},
    {"text": "Didn’t forget updating attendance", "label": 3},
    {"text": "Didn’t fail to record face recognization system today", "label": 3},
    {"text": "Didn’t forget the face recognization system check", "label": 3},
    {"text": "Didn’t miss today’s face recognization system entry", "label": 3},
    {"text": "Didn’t forget to submit attendance", "label": 3},
    {"text": "Didn’t fail to update face recognization system entry", "label": 3},
    {"text": "Didn’t forget about face recognization system completely", "label": 3},
    {"text": "Didn’t skip today’s face recognization system log", "label": 3},
    {"text": "Didn’t forget my attendance update", "label": 3},
    {"text": "Didn’t miss to update face recognization system", "label": 3},
    {"text": "Didn’t forget face recognization system portal update", "label": 3},
    {"text": "Didn’t fail to attend face recognization system today", "label": 3},
    {"text": "Didn’t forget my daily face recognization system", "label": 3},
    {"text": "Didn’t miss the face recognization system login", "label": 3},
    {"text": "Didn’t forget to do face recognization system", "label": 3},
    {"text": "Didn’t miss filling face recognization system portal", "label": 3},
    {"text": "Didn’t forget face recognization system entry", "label": 3},
    {"text": "Didn’t fail to attend face recognization system", "label": 3},
    {"text": "Didn’t miss face recognization system filling today", "label": 3},
    {"text": "Didn’t forget today’s entry in face recognization system", "label": 3},
    {"text": "Didn’t fail to complete face recognization system entry", "label": 3},
]


# ------------------------------
# Helper: preprocessing function
# ------------------------------
def preprocess(text: str) -> str:
    text = text.lower().strip()
    # keep alnum and spaces
    text = ''.join(c for c in text if c.isalnum() or c.isspace())
    text = " ".join(text.split())
    return text

# Preprocess dataset texts
for item in data:
    item["text"] = preprocess(item["text"])

# Shuffle for randomness
random.seed(42)
random.shuffle(data)

# Dataset -> HF Dataset and train/test split
ds = Dataset.from_list(data)
ds = ds.train_test_split(test_size=0.15, seed=42)
train_ds = ds["train"]
eval_ds = ds["test"]

# ------------------------------
# Tokenize & prepare
# ------------------------------
MODEL_NAME = "distilbert-base-uncased"
tokenizer = DistilBertTokenizerFast.from_pretrained(MODEL_NAME)

def tokenize_fn(batch):
    return tokenizer(batch["text"], padding="max_length", truncation=True, max_length=64)

train_ds = train_ds.map(tokenize_fn, batched=True)
eval_ds = eval_ds.map(tokenize_fn, batched=True)

train_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
eval_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

# ------------------------------
# Model & Trainer
# ------------------------------
model = DistilBertForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=4)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average="weighted")
    prec = precision_score(labels, preds, average="weighted", zero_division=0)
    rec = recall_score(labels, preds, average="weighted", zero_division=0)
    return {"accuracy": acc, "f1": f1, "precision": prec, "recall": rec}

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    weight_decay=0.01,
    label_smoothing_factor=0.05,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    logging_dir="./logs",
    logging_steps=50,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)
# ------------------------------
# Train
# ------------------------------
trainer.train()

# ------------------------------
# Save
# ------------------------------
SAVE_DIR = "./face recognization system_classifier"
model.save_pretrained(SAVE_DIR)
tokenizer.save_pretrained(SAVE_DIR)
print(f"✅ Model and tokenizer saved to {SAVE_DIR}")
